/*
This source file is part of Smyle, a database library.
For up-to-date information, see http://www.drjava.de/smyle
Copyright (C) 2001 Stefan Reich (doc@drjava.de)

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

For full license text, see doc/license/lgpl.txt in this distribution
*/

package drjava.smyle;

import java.io.*;

/** encapsulates either an IOException thrown by the file system
    libraries or a higher level IO exception generated by Smyle
    itself */
public class SmyleIOException extends SmyleException {
  IOException e;
  
  public SmyleIOException(IOException e) {
    super(e.toString());
  }
  
  public SmyleIOException(String msg) {
    super(msg);
  }
  
  /** return value might be null */
  public IOException getRootException() {
    return e;
  }
}
